### PR TITLE
BVAL-592 Example fixes

### PR DESCRIPTION
**Pull request by gunnarmorling**

### CODE REVIEW

**Comment by gunnarmorling** [comment]
Hi, @gsmet. Can we merge this one?

**Comment by gsmet** [comment]
It's already merged. Forgot to close it!

**Comment by gunnarmorling** [comment]
Ah, cool. So it's part of the last release actually?

2017-05-19 9:58 GMT+02:00 Guillaume Smet <notifications@github.com>:

**Comment by gsmet** [comment]
Yes, it is.

**Pull request closed without merging**
