### PR TITLE
BVAL-583 Use the common theme for the asciidoc output

### PR DESCRIPTION
**Pull request by gsmet**
* https://hibernate.atlassian.net/browse/BVAL-583

I had prepared this for a while. FWIW, I didn't include the logo in the HTML as I did it for the TCK documentation so that the spec is still self contained.

### CODE REVIEW

**Comment by gunnarmorling** [comment]
> so that the spec is still self contained

WDYM by that?

**Comment by gunnarmorling** [comment]
Rebased and applied. Thanks, @gsmet!

**Comment by gsmet** [comment]
So that we don't have to have the logo on the side. I think it's better if the spec is all self contained and you don't need additional files (logo, CSS, whatever).

**Comment by gunnarmorling** [comment]
Ah, you mean the rendered output. Ok.

**Pull request closed without merging**
