### PR TITLE
BVAL-455 Updating spec for 2.0 XML schemas

### PR DESCRIPTION
**Pull request by gunnarmorling**
https://hibernate.atlassian.net/browse/BVAL-455

### CODE REVIEW

**Comment by hendrikebbers** [comment]
Until now we do not have a schema at "http://xmlns.jcp.org/xml/ns/validation/mapping validation-mapping-2.0.xsd". I have no idea how complex it will be to upload such a file to the jcp domain. As said I think that the change is a good one but maybe we should check that we can easily upload new xsd files before we change it.

**Comment by gunnarmorling** [comment]
Hey @hendrikebbers, thanks for the feedback!

Yes, we need to work with the folks at JCP how to get the files there; there is [BVAL-531](https://hibernate.atlassian.net/browse/BVAL-531) for tracking this. I don't expect big problems given that the other schema files are hosted there, too. I'll ask the PMO what the process is, I suppose it may take some time to make it happen.

**Comment by hferentschik** [comment]
+1 for the change, but let's double check with the process of getting this files hosted first.

**Comment by gunnarmorling** [comment]
I've sent a mail to the PMO, asking about the process. But we can move
forward with the change for now IMO, as we can live without the files
exposed through that URI for the time being and then have the final
versions hosted once we don't expect any further changes (nothing really
mandates that schema files are available through the URI given in the
namespace, it's just a common expectation people have).

**Comment by hendrikebbers** [comment]
+1
Uploading the final version should be fine

Von meinem iPhone gesendet

**Comment by gsmet** [comment]
Amended and merged. Thanks!

**Pull request closed without merging**
